name: emmentalembed
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.10
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - biopython
  - scikit-learn
  - jupyter
  - ipykernel
  - pip
  - pip:
    - -e .