name: plm
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - numpy>=1.22,<=1.24.3
  - pytorch
  - cudatoolkit
  - pandas
  - biopython
  - pip
  - pip:
    - ankh
    - fair-esm
    - jax-unirep
    - transformers>=4.20.0
    - tensorflow>=2.0
    - pathlib